"""
Aura v2 — Automated Bug Bounty Submission Engine
=================================================
Closes the full pipeline: Discovery → Hunt → AI Report → SUBMIT.

Supports:
  - Intigriti: Submit via official API (no manual copy-paste)
  - HackerOne: Submit via H1 API
  - Dry Run: Preview the submission payload locally (no network call)

Usage:
    aura --submit reports/report_*.md
    aura --submit reports/report_*.md --dry-run      (preview only)
    aura --submit reports/report_*.md --platform h1  (HackerOne)

Credentials in .env:
    INTIGRITI_EMAIL=you@example.com
    INTIGRITI_PASSWORD=yourpassword
    INTIGRITI_PROGRAM_ID=ici-paris-xl   (from the program URL)
    H1_API_TOKEN=your_hackerone_token   (optional)
    H1_PROGRAM_HANDLE=ici_paris_xl       (optional)
"""

import json
import os
import re
import sys
from datetime import datetime
from pathlib import Path
from typing import Optional

import httpx


# ─── Severity Mappings ─────────────────────────────────────────────────────────
INTIGRITI_SEVERITY_MAP = {
    "CRITICAL": 5,
    "HIGH": 4,
    "MEDIUM": 3,
    "LOW": 2,
    "INFORMATIONAL": 1,
}

# CVSS score → severity label
def cvss_to_severity(score: float) -> str:
    if score >= 9.0: return "CRITICAL"
    if score >= 7.0: return "HIGH"
    if score >= 4.0: return "MEDIUM"
    if score >= 0.1: return "LOW"
    return "INFORMATIONAL"


class IntigritiSubmitter:
    """
    Submits bug reports to Intigriti via their REST API.
    Handles authentication, field mapping, and PoC attachment.
    """

    BASE_URL = "https://api.intigriti.com/core/researcher"
    AUTH_URL = "https://api.intigriti.com/authentication/authenticate"

    def __init__(
        self,
        email: Optional[str] = None,
        password: Optional[str] = None,
        program_id: Optional[str] = None,
        dry_run: bool = False,
    ):
        self.email = email or os.getenv("INTIGRITI_EMAIL", "")
        self.password = password or os.getenv("INTIGRITI_PASSWORD", "")
        self.program_id = program_id or os.getenv("INTIGRITI_PROGRAM_ID", "")
        self.dry_run = dry_run
        self.token: Optional[str] = None

    def _authenticate(self) -> bool:
        """Logs in to Intigriti and stores the Bearer token."""
        if not self.email or not self.password:
            print("❌ INTIGRITI_EMAIL or INTIGRITI_PASSWORD not set in .env")
            return False

        print(f"  🔐 Authenticating to Intigriti as {self.email}...")
        try:
            resp = httpx.post(
                self.AUTH_URL,
                json={"email": self.email, "password": self.password},
                timeout=15,
            )
            data = resp.json()
            token = data.get("token") or data.get("access_token") or data.get("accessToken")
            if token:
                self.token = token
                print("  ✅ Authentication successful!")
                return True
            else:
                print(f"  ❌ Auth failed. Response: {json.dumps(data)[:200]}")
                return False
        except Exception as e:
            print(f"  ❌ Auth error: {e}")
            return False

    def _parse_report(self, report_path: str) -> dict:
        """
        Parses a Markdown report generated by ai_analyst.py and extracts
        structured fields for submission.
        """
        report_path = Path(report_path)
        if not report_path.exists():
            print(f"❌ Report file not found: {report_path}")
            return {}

        content = report_path.read_text(encoding="utf-8")

        # Extract key fields from Markdown
        title_match = re.search(r'^# (.+)$', content, re.MULTILINE)
        summary_match = re.search(r'## Summary\s*\n(.+?)(?=\n##)', content, re.DOTALL)
        impact_match = re.search(r'## Impact\s*\n(.+?)(?=\n##)', content, re.DOTALL)
        steps_match = re.search(r'## Steps to Reproduce.*?\n(.+?)(?=\n##)', content, re.DOTALL)
        cvss_match = re.search(r'\*\*Score:\*\*\s*([\d.]+)', content)
        severity_match = re.search(r'\*\*Severity:\*\*\s*(\w+)', content)
        url_match = re.search(r'(https?://[^\s\]]+(?:/api|/user|/cart|/address)[^\s\]]*)', content)

        title = title_match.group(1).strip() if title_match else "BOLA/IDOR Vulnerability"
        summary = summary_match.group(1).strip() if summary_match else content[:500]
        impact = impact_match.group(1).strip() if impact_match else "Unauthorized data access"
        steps = steps_match.group(1).strip() if steps_match else "See report for details"
        cvss_score = float(cvss_match.group(1)) if cvss_match else 6.5
        severity_raw = severity_match.group(1).upper() if severity_match else "MEDIUM"
        affected_url = url_match.group(1) if url_match else ""

        return {
            "title": title,
            "summary": summary,
            "impact": impact,
            "steps_to_reproduce": steps,
            "cvss_score": cvss_score,
            "severity": severity_raw,
            "severity_id": INTIGRITI_SEVERITY_MAP.get(severity_raw, 3),
            "affected_url": affected_url,
            "full_report": content,
            "report_filename": report_path.name,
        }

    def _build_intigriti_payload(self, parsed: dict) -> dict:
        """Builds the Intigriti submission payload."""
        return {
            "programId": self.program_id,
            "title": parsed["title"],
            "description": (
                f"## Summary\n{parsed['summary']}\n\n"
                f"## Impact\n{parsed['impact']}\n\n"
                f"## Steps to Reproduce\n{parsed['steps_to_reproduce']}"
            ),
            "severity": {
                "id": parsed["severity_id"],
                "vector": f"CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N",
                "score": parsed["cvss_score"],
            },
            "type": {
                "id": 1,  # 1 = Bug
                "name": "Bug"
            },
            "affectedAssets": [
                {
                    "value": parsed["affected_url"],
                    "type": "URL",
                }
            ] if parsed["affected_url"] else [],
            "status": {
                "id": 1,  # Draft
                "name": "Draft"
            }
        }

    def submit(self, report_path: str) -> bool:
        """
        Main submission method.
        Parses the Markdown report and submits it to Intigriti.
        Returns True on success.
        """
        print(f"\n{'='*65}")
        print(f"🚀 AURA v2 — Intigriti Auto-Submitter")
        if self.dry_run:
            print(f"⚠️  DRY RUN MODE — No actual submission will be made")
        print(f"📄 Report: {report_path}")
        print(f"{'='*65}\n")

        # Parse the report
        parsed = self._parse_report(report_path)
        if not parsed:
            return False

        print(f"  📋 Title     : {parsed['title']}")
        print(f"  🎯 Severity  : {parsed['severity']} (CVSS {parsed['cvss_score']})")
        print(f"  🌐 Asset URL : {parsed['affected_url'] or 'not detected'}")
        print(f"  📊 Program   : {self.program_id or 'not set'}")

        # Build payload
        payload = self._build_intigriti_payload(parsed)

        if self.dry_run:
            print(f"\n{'─'*65}")
            print(f"📦 DRY RUN — Payload that WOULD be submitted:")
            print(f"{'─'*65}")
            print(json.dumps(payload, indent=2))
            print(f"{'─'*65}")
            print(f"\n✅ Dry run complete! Use --submit without --dry-run to actually submit.")
            return True

        # Authenticate
        if not self._authenticate():
            return False

        # Submit
        headers = {
            "Authorization": f"Bearer {self.token}",
            "Content-Type": "application/json",
        }

        print(f"\n  📡 Submitting to Intigriti API...")
        try:
            resp = httpx.post(
                f"{self.BASE_URL}/submission",
                json=payload,
                headers=headers,
                timeout=30,
            )

            if resp.status_code in (200, 201):
                data = resp.json()
                submission_id = data.get("id") or data.get("submissionId") or "unknown"
                print(f"\n{'='*65}")
                print(f"🎉 SUBMISSION SUCCESSFUL!")
                print(f"{'='*65}")
                print(f"  ✅ Submission ID : {submission_id}")
                print(f"  🔗 Review at     : https://app.intigriti.com/researcher/submissions/{submission_id}")
                print(f"{'='*65}\n")
                return True
            else:
                print(f"\n  ❌ Submission failed: HTTP {resp.status_code}")
                print(f"  Response: {resp.text[:300]}")
                return False

        except Exception as e:
            print(f"\n  ❌ Network error: {e}")
            return False


class HackerOneSubmitter:
    """
    Submits bug reports to HackerOne via their REST API.
    Requires H1_API_TOKEN and H1_PROGRAM_HANDLE in .env
    """

    BASE_URL = "https://api.hackerone.com/v1"

    def __init__(
        self,
        api_token: Optional[str] = None,
        program_handle: Optional[str] = None,
        username: Optional[str] = None,
        dry_run: bool = False,
    ):
        self.api_token = api_token or os.getenv("H1_API_TOKEN", "")
        self.program_handle = program_handle or os.getenv("H1_PROGRAM_HANDLE", "")
        self.username = username or os.getenv("H1_USERNAME", "")
        self.dry_run = dry_run

    def submit(self, parsed: dict) -> bool:
        """Submits a parsed report to HackerOne."""
        if not self.api_token or not self.program_handle:
            print("❌ H1_API_TOKEN or H1_PROGRAM_HANDLE not set in .env")
            return False

        payload = {
            "data": {
                "type": "report",
                "attributes": {
                    "team_handle": self.program_handle,
                    "title": parsed["title"],
                    "vulnerability_information": (
                        f"## Summary\n{parsed['summary']}\n\n"
                        f"## Impact\n{parsed['impact']}\n\n"
                        f"## Steps to Reproduce\n{parsed['steps_to_reproduce']}"
                    ),
                    "severity_rating": parsed["severity"].lower(),
                    "cvss_vector_string": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N",
                    "weakness_id": 285,  # CWE-285: Improper Authorization
                }
            }
        }

        if self.dry_run:
            print(f"\n📦 HackerOne DRY RUN Payload:")
            print(json.dumps(payload, indent=2))
            return True

        try:
            resp = httpx.post(
                f"{self.BASE_URL}/reports",
                json=payload,
                auth=(self.username, self.api_token),
                timeout=30,
            )
            if resp.status_code in (200, 201):
                data = resp.json()
                report_id = data.get("data", {}).get("id", "unknown")
                print(f"🎉 HackerOne submission successful! Report #{report_id}")
                return True
            else:
                print(f"❌ HackerOne error: HTTP {resp.status_code} — {resp.text[:200]}")
                return False
        except Exception as e:
            print(f"❌ HackerOne network error: {e}")
            return False


def run_submit(
    report_path: str,
    platform: str = "intigriti",
    dry_run: bool = False,
) -> bool:
    """
    CLI runner for `aura --submit <report.md>`.
    """
    from dotenv import load_dotenv
    load_dotenv()

    if platform.lower() in ("intigriti", "i"):
        submitter = IntigritiSubmitter(dry_run=dry_run)
        return submitter.submit(report_path)

    elif platform.lower() in ("hackerone", "h1"):
        # Parse the report first
        intigriti = IntigritiSubmitter(dry_run=True)
        parsed = intigriti._parse_report(report_path)
        if not parsed:
            return False
        h1 = HackerOneSubmitter(dry_run=dry_run)
        return h1.submit(parsed)

    else:
        print(f"❌ Unknown platform: {platform}. Use 'intigriti' or 'h1'")
        return False


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python -m aura.modules.submitter_v2 <report.md> [--dry-run] [--platform h1]")
        sys.exit(1)

    _path = sys.argv[1]
    _dry = "--dry-run" in sys.argv
    _plat = "h1" if "--platform" in sys.argv and "h1" in sys.argv else "intigriti"
    run_submit(_path, platform=_plat, dry_run=_dry)
