import os
from typing import Dict, Optional
from rich.console import Console

console = Console()

class PoCSynthesizer:
    """
    v17.0 The Zero-Rejection Engine: Automated PoC Generator.
    Generates ready-to-run Python scripts and curl commands to provide
    undeniable proof of exploitability to bug bounty triagers.
    """
    def __init__(self, output_dir: str = "pocs"):
        self.output_dir = output_dir
        if not os.path.exists(self.output_dir):
            os.makedirs(self.output_dir)

    def generate_curl_poc(self, finding: Dict) -> str:
        """Generates a copy-pasteable curl command for the vulnerability."""
        url = finding.get("url", finding.get("target", ""))
        method = finding.get("method", "GET").upper()
        headers = finding.get("headers", {})
        data = finding.get("data", "")
        
        cmd = f"curl -i -s -k -X '{method}' '{url}'"
        
        for k, v in headers.items():
            # Escape single quotes in headers
            v_escaped = str(v).replace("'", "'\\''")
            cmd += f" \\\n    -H '{k}: {v_escaped}'"
            
        if data:
            data_escaped = str(data).replace("'", "'\\''")
            cmd += f" \\\n    --data '{data_escaped}'"
            
        return cmd

    def generate_python_poc(self, finding: Dict) -> str:
        """Generates a standalone Python exploit script."""
        url = finding.get("url", finding.get("target", ""))
        method = finding.get("method", "GET").upper()
        headers = finding.get("headers", {})
        data = finding.get("data", "")
        f_type = finding.get("type", finding.get("finding_type", "Unknown Vulnerability"))
        
        script = f'''#!/usr/bin/env python3
# -----------------------------------------------------------------------------
# Automated Proof-of-Concept Exploit
# Vulnerability: {f_type}
# Target: {url}
# Generated by Aura (Zero-Rejection Engine)
# -----------------------------------------------------------------------------

import requests
from urllib3.exceptions import InsecureRequestWarning

# Suppress insecure request warnings for proxy interception
requests.packages.urllib3.disable_warnings(category=InsecureRequestWarning)

def exploit():
    target_url = "{url}"
    
    headers = {repr(headers)}
    
    data = {repr(data)}
    
    print(f"[*] Sending {method} request to {{target_url}}...")
    
    try:
'''
        if method == "POST":
            script += '        response = requests.post(target_url, headers=headers, data=data, verify=False, timeout=10)\n'
        elif method == "PUT":
            script += '        response = requests.put(target_url, headers=headers, data=data, verify=False, timeout=10)\n'
        else:
            script += '        response = requests.get(target_url, headers=headers, verify=False, timeout=10)\n'
            
        script += '''
        print(f"[+] Status Code: {response.status_code}")
        print("[-] Response Headers:")
        for k, v in response.headers.items():
            print(f"    {k}: {v}")
            
        print("\\n[-] Response Body snippet:")
        print(response.text[:500] + ("..." if len(response.text) > 500 else ""))
        
        # NOTE: Add custom validation logic below this line to verify the exploit worked.
        # e.g., if "root:x:0:0" in response.text: print("[!] Exploit successful!")
        
    except requests.exceptions.RequestException as e:
        print(f"[!] Request failed: {e}")

if __name__ == "__main__":
    exploit()
'''
        return script

    def save_poc(self, finding: Dict) -> Optional[str]:
        """Saves the generated Python PoC to a file and returns the file path."""
        url = finding.get("url", finding.get("target", ""))
        if not url:
            return None
            
        import urllib.parse
        parsed = urllib.parse.urlparse(url)
        domain = parsed.netloc.replace(":", "_") if parsed.netloc else "unknown_target"
        f_type = finding.get("type", finding.get("finding_type", "vuln")).replace(" ", "_").replace("/", "_")
        
        # Create a safe filename
        import re
        safe_type = re.sub(r'[^a-zA-Z0-9_\-]', '', f_type)
        safe_domain = re.sub(r'[^a-zA-Z0-9_\-]', '', domain)
        filename = f"poc_{safe_type}_{safe_domain}.py"
        filepath = os.path.join(self.output_dir, filename)
        
        try:
            script_content = self.generate_python_poc(finding)
            with open(filepath, "w", encoding="utf-8") as f:
                f.write(script_content)
            
            # Make the script executable on Unix-like systems
            try:
                os.chmod(filepath, 0o755)
            except:
                pass 
                
            console.print(f"[bold green][+] PoC Exploit Script successfully synthesized: {filepath}[/bold green]")
            return filepath
        except Exception as e:
            console.print(f"[bold red][!] Failed to generate PoC script: {e}[/bold red]")
            return None
