import logging
import json
import os
from datetime import datetime
from aura.core.brain import AuraBrain

logger = logging.getLogger("aura")

class BountyBroker:
    """
    v39.0: The Bounty Broker
    Automates the generation of professional, platform-ready bug bounty reports.
    """
    def __init__(self, output_dir="bounties"):
        self.output_dir = output_dir
        self.brain = AuraBrain()
        if not os.path.exists(self.output_dir):
            os.makedirs(self.output_dir)

    async def generate_report(self, finding: dict, platform: str = "intigriti") -> str:
        """Generates a full markdown report for a specific finding."""
        logger.info(f"Bounty Broker: Generating {platform} report for {finding.get('type')}")
        
        # 1. Synthesize narrative using AI
        report_data = await self._synthesize_ai_content(finding, platform)
        
        # 2. Fill template
        if platform.lower() == "intigriti":
            formatted_report = self._fill_intigriti_template(finding, report_data)
        elif platform.lower() == "hackerone":
            formatted_report = self._fill_hackerone_template(finding, report_data)
        else:
            formatted_report = self._fill_generic_template(finding, report_data)

        # 3. Save to file
        filename = f"{platform.upper()}_{finding.get('type').replace(' ', '_')}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"
        filepath = os.path.join(self.output_dir, filename)
        
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(formatted_report)
            
        return filepath

    async def _synthesize_ai_content(self, finding: dict, platform: str) -> dict:
        """Uses Gemini to write the impact, description, and steps."""
        prompt = (
            f"As a Professional Security Researcher, write a high-impact bug bounty report section for a {finding.get('type')} vulnerability.\n"
            f"Finding Data: {json.dumps(finding)}\n"
            f"Platform: {platform}\n\n"
            "Respond ONLY in JSON with these keys: 'description', 'impact', 'steps_to_reproduce', 'remediation'. "
            "The impact should focus on business risk (e.g., GDPR, financial loss, data breach). "
            "Steps should be clear and numbered."
        )
        
        try:
            raw = self.brain._call_ai(prompt, use_cache=False)
            # Basic cleanup if AI returns markdown wrapper
            clean_raw = raw.strip().replace("```json", "").replace("```", "").strip()
            return json.loads(clean_raw)
        except Exception as e:
            logger.error(f"Bounty Broker AI synthesis failed: {e}")
            return {
                "description": finding.get("content", "N/A"),
                "impact": finding.get("impact_desc", "Significant risk to data integrity."),
                "steps_to_reproduce": "1. Access the target URL.\n2. Execute the provided payload.",
                "remediation": finding.get("remediation_fix", "Patch the affected endpoint.")
            }

    def _fill_intigriti_template(self, finding, ai_data):
        return f"""# [Aura Generated] Vulnerability Report: {finding.get('type')}

## 📝 Description
{ai_data.get('description')}

## 🎯 Target Asset
- **URL:** {finding.get('url', finding.get('evidence_url', 'N/A'))}
- **Parameter:** {finding.get('param', 'N/A')}
- **Severity:** {finding.get('severity', 'HIGH')}

## 💥 Impact
{ai_data.get('impact')}

## 🛠️ Steps to Reproduce
{ai_data.get('steps_to_reproduce')}

## 🔗 Evidence & Proof of Concept
- **Payload:** `{finding.get('payload', 'See Context')}`
- **POC Link:** {finding.get('poc_link', 'N/A')}

### Raw HTTP Request
```http
{finding.get('raw_request', 'N/A')}
```

## ✅ Remediation
{ai_data.get('remediation')}

---
*Report generated autonomously by Aura v39.0 (Bounty Broker)*
"""

    def _fill_hackerone_template(self, finding, ai_data):
        # Similar to Intigriti but using HackerOne's preferred terminology
        return f"""# Summary
{ai_data.get('description')}

## Impact
{ai_data.get('impact')}

## Steps to Reproduce
{ai_data.get('steps_to_reproduce')}

## Details
- Vulnerability Type: {finding.get('type')}
- Exploit String: `{finding.get('payload', 'N/A')}`

## Supporting Material
> {finding.get('proof', 'N/A')}

---
Report generated by Aura Sentinel.
"""

    def _fill_generic_template(self, finding, ai_data):
        return f"# Finding: {finding.get('type')}\n\n{ai_data.get('description')}\n\nImpact: {ai_data.get('impact')}"
