"""
Aura v26.0 — Intel Gems Extractor 💎
=====================================
Filters the sovereign database (aura_intel.db) to extract the highest-value
findings. Produces a formatted Markdown report ready for bug bounty submission.
"""
import sqlite3
import os
import json
from datetime import datetime

DB_PATH = "aura_intel.db"
REPORT_DIR = "reports"

# Target filter — change to None to extract ALL targets
TARGET_FILTER = "intel"

HIGH_VALUE_TYPES = [
    "idor", "bola", "ssrf", "rce", "sql", "xss", "lfi", "auth",
    "bypass", "logic flaw", "information disclosure", "aws secret",
    "broken", "privilege", "exposure", "leak", "mass assignment",
    "jwt", "oauth", "cors", "graphql", "injection"
]

def load_gems():
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    c = conn.cursor()

    # Get target IDs for the filter
    if TARGET_FILTER:
        c.execute(
            "SELECT id, value FROM targets WHERE value LIKE ?",
            (f"%{TARGET_FILTER}%",)
        )
    else:
        c.execute("SELECT id, value FROM targets")

    targets = c.fetchall()
    target_map = {t["id"]: t["value"] for t in targets}

    if not target_map:
        print(f"[!] No targets found matching '{TARGET_FILTER}'.")
        conn.close()
        return []

    print(f"[*] Found {len(target_map)} matching target(s): {list(target_map.values())}")

    target_ids_str = ",".join(str(i) for i in target_map.keys())

    # Pull ALL findings for those targets
    c.execute(
        f"SELECT * FROM findings WHERE target_id IN ({target_ids_str}) ORDER BY severity, id DESC"
    )
    all_findings = [dict(r) for r in c.fetchall()]
    conn.close()

    print(f"[*] Total findings in DB for target(s): {len(all_findings)}")

    # Filter: only HIGH/CRITICAL severity OR known high-value types
    gems = []
    seen_signatures = set()

    for f in all_findings:
        ftype = (f.get("finding_type") or "").lower()
        sev = (f.get("severity") or "").upper()
        content = f.get("content") or ""

        # Dedup by type+content prefix
        sig = f"{ftype}_{content[:60]}"
        if sig in seen_signatures:
            continue
        seen_signatures.add(sig)

        is_high_value_type = any(kw in ftype for kw in HIGH_VALUE_TYPES)
        is_high_sev = sev in ("CRITICAL", "HIGH", "EXCEPTIONAL")

        if is_high_value_type or is_high_sev:
            f["target_name"] = target_map.get(f.get("target_id"), "Unknown")
            gems.append(f)

    # Sort: CRITICAL first, then HIGH
    sev_order = {"EXCEPTIONAL": 0, "CRITICAL": 1, "HIGH": 2, "MEDIUM": 3, "LOW": 4}
    gems.sort(key=lambda x: sev_order.get((x.get("severity") or "LOW").upper(), 5))

    print(f"[💎] Gems extracted: {len(gems)} unique high-value findings.")
    return gems


def generate_gem_report(gems: list) -> str:
    os.makedirs(REPORT_DIR, exist_ok=True)
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    report_path = os.path.join(REPORT_DIR, f"intel_gems_report_{ts}.md")

    critical = [g for g in gems if (g.get("severity") or "").upper() in ("CRITICAL", "EXCEPTIONAL")]
    high = [g for g in gems if (g.get("severity") or "").upper() == "HIGH"]
    medium = [g for g in gems if (g.get("severity") or "").upper() == "MEDIUM"]

    all_lines = [
        "# 💎 Intel.com — Aura Sovereign Intelligence: Gem Report",
        f"> Generated by Aura v27.0 Chronos Protocol  |  {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        "",
        "---",
        "",
        "## 📊 Executive Summary",
        "",
        "| Severity   | Count |",
        "|------------|-------|",
        f"| 🔴 Critical / Exceptional | {len(critical)} |",
        f"| 🟠 High    | {len(high)} |",
        f"| 🟡 Medium  | {len(medium)} |",
        f"| **Total**  | **{len(gems)}** |",
        "",
        "---",
        "",
    ]

    def format_section(title, emoji, findings):
        section = [f"## {emoji} {title} ({len(findings)} findings)", ""]
        if not findings:
            section += ["*None identified.*", ""]
            return section
        for i, f in enumerate(findings, 1):
            ftype = f.get("finding_type") or "Unknown"
            content = f.get("content") or "No details."
            target = f.get("target_name") or "intel.com"
            sev = f.get("severity") or "N/A"
            owasp = f.get("owasp") or "N/A"
            mitre = f.get("mitre") or "N/A"
            proof = f.get("proof") or None
            created = f.get("created_at") or "N/A"
            section += [
                f"### {i}. {ftype}",
                f"- **Target:** `{target}`",
                f"- **Severity:** `{sev}`",
                f"- **OWASP:** {owasp}",
                f"- **MITRE ATT&CK:** {mitre}",
                f"- **Discovered:** {created}",
                "",
                "**Details:**",
                "```",
                content[:1500],
                "```",
            ]
            if proof:
                section += ["", f"**Evidence:** `{proof}`"]
            section += ["", "---", ""]
        return section

    all_lines += format_section("CRITICAL / EXCEPTIONAL Findings", "🔴", critical)
    all_lines += format_section("HIGH Severity Findings", "🟠", high)
    all_lines += format_section("MEDIUM Severity Findings (Top 20)", "🟡", medium[:20])

    with open(report_path, "w", encoding="utf-8") as fp:
        fp.write("\n".join(all_lines))

    print(f"\n[✅] Intel Gems Report saved: {report_path}")
    return report_path


if __name__ == "__main__":
    print("=" * 60)
    print("  💎 Aura Intel Gems Extractor — v26.0 Turbine Engine")
    print("=" * 60)
    gems = load_gems()
    if gems:
        path = generate_gem_report(gems)
        print(f"\n[🚀] Ready for submission: {path}")
    else:
        print("[!] No gems found. Try adjusting TARGET_FILTER or running a fresh scan.")
